baseURL = "https://www.xfce.org/"
title = "Xfce Desktop Environment"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true
disableKinds = ["taxonomy", "term"]

[params]
  staticMedia = "//cdn.xfce.org"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"
    isPlainText = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[[module.mounts]]
  source = "content"
  target = "content"
  lang = "en"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ar"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "bg"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ca"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "cs"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "da"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "de"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "el"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "en-AU"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "en-GB"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "es"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "fa-IR"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "fr"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "gl"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "he"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "hu"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "id"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "it"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ja"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "kk"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ko"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "lt"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ms"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "nb"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "nl"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "oc"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "pl"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "pt"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "pt-BR"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ro"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "ru"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "sk"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "sl"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "sq"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "sr"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "sv"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "th"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "tr"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "uk"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "vi"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "zh-CN"

[[module.mounts]]
  source = "content"
  target = "content"
  lang = "zh-TW"
