[en]
  languageName = "English"
  weight = 1
  contentDir = "content"

[ar]
  languageName = "Arabic"
  weight = 2
  contentDir = "content"

[bg]
  languageName = "Bulgarian"
  weight = 3
  contentDir = "content"

[ca]
  languageName = "Catalan"
  weight = 4
  contentDir = "content"

[cs]
  languageName = "Czech"
  weight = 5
  contentDir = "content"

[da]
  languageName = "Danish"
  weight = 6
  contentDir = "content"

[de]
  languageName = "German"
  weight = 7
  contentDir = "content"

[el]
  languageName = "Greek"
  weight = 8
  contentDir = "content"

[en-AU]
  languageName = "English (Australia)"
  weight = 9
  contentDir = "content"

[en-GB]
  languageName = "English (United Kingdom)"
  weight = 10
  contentDir = "content"

[es]
  languageName = "Spanish (Castilian)"
  weight = 11
  contentDir = "content"

[fa-IR]
  languageName = "Persian"
  weight = 12
  contentDir = "content"

[fr]
  languageName = "French"
  weight = 13
  contentDir = "content"

[gl]
  languageName = "Galician"
  weight = 14
  contentDir = "content"

[he]
  languageName = "Hebrew"
  weight = 15
  contentDir = "content"

[hu]
  languageName = "Hungarian"
  weight = 16
  contentDir = "content"

[id]
  languageName = "Indonesian"
  weight = 17
  contentDir = "content"

[it]
  languageName = "Italian"
  weight = 18
  contentDir = "content"

[ja]
  languageName = "Japanese"
  weight = 19
  contentDir = "content"

[kk]
  languageName = "Kazakh"
  weight = 20
  contentDir = "content"

[ko]
  languageName = "Korean"
  weight = 21
  contentDir = "content"

[lt]
  languageName = "Lithuanian"
  weight = 22
  contentDir = "content"

[ms]
  languageName = "Malay"
  weight = 23
  contentDir = "content"

[nb]
  languageName = "Norwegian Bokmal"
  weight = 24
  contentDir = "content"

[nl]
  languageName = "Dutch"
  weight = 25
  contentDir = "content"

[oc]
  languageName = "Occitan"
  weight = 26
  contentDir = "content"

[pl]
  languageName = "Polish"
  weight = 27
  contentDir = "content"

[pt]
  languageName = "Portuguese"
  weight = 28
  contentDir = "content"

[pt-BR]
  languageName = "Portuguese (Brazilian)"
  weight = 29
  contentDir = "content"

[ro]
  languageName = "Romanian"
  weight = 30
  contentDir = "content"

[ru]
  languageName = "Russian"
  weight = 31
  contentDir = "content"

[sk]
  languageName = "Slovak"
  weight = 32
  contentDir = "content"

[sl]
  languageName = "Slovenian"
  weight = 33
  contentDir = "content"

[sq]
  languageName = "Albanian"
  weight = 34
  contentDir = "content"

[sr]
  languageName = "Serbian"
  weight = 35
  contentDir = "content"

[sv]
  languageName = "Swedish"
  weight = 36
  contentDir = "content"

[th]
  languageName = "Thai"
  weight = 37
  contentDir = "content"

[tr]
  languageName = "Turkish"
  weight = 38
  contentDir = "content"

[uk]
  languageName = "Ukrainian"
  weight = 39
  contentDir = "content"

[vi]
  languageName = "Vietnamese"
  weight = 40
  contentDir = "content"

[zh-CN]
  languageName = "Chinese (Simplified)"
  weight = 41
  contentDir = "content"

[zh-TW]
  languageName = "Chinese (Traditional)"
  weight = 42
  contentDir = "content"
