[en]
  label = "English"
  contentDir = "content"

[ar]
  label = "Arabic"
  contentDir = "generated/ar"

[bg]
  label = "Bulgarian"
  contentDir = "generated/bg"

[ca]
  label = "Catalan"
  contentDir = "generated/ca"

[cs]
  label = "Czech"
  contentDir = "generated/cs"

[da]
  label = "Danish"
  contentDir = "generated/da"

[de]
  label = "German"
  contentDir = "generated/de"

[el]
  label = "Greek"
  contentDir = "generated/el"

[en_AU]
  label = "English (Australia)"
  locale = "en-AU"
  contentDir = "generated/en_AU"

[en_GB]
  label = "English (United Kingdom)"
  locale = "en-GB"
  contentDir = "generated/en_GB"

[es]
  label = "Spanish (Castilian)"
  contentDir = "generated/es"

[fa_IR]
  label = "Persian"
  locale = "fa-IR"
  contentDir = "generated/fa_IR"

[fr]
  label = "French"
  contentDir = "generated/fr"

[gl]
  label = "Galician"
  contentDir = "generated/gl"

[he]
  label = "Hebrew"
  contentDir = "generated/he"

[hu]
  label = "Hungarian"
  contentDir = "generated/hu"

[id]
  label = "Indonesian"
  contentDir = "generated/id"

[it]
  label = "Italian"
  contentDir = "generated/it"

[ja]
  label = "Japanese"
  contentDir = "generated/ja"

[kk]
  label = "Kazakh"
  contentDir = "generated/kk"

[ko]
  label = "Korean"
  contentDir = "generated/ko"

[lt]
  label = "Lithuanian"
  contentDir = "generated/lt"

[ms]
  label = "Malay"
  contentDir = "generated/ms"

[nb]
  label = "Norwegian Bokmal"
  contentDir = "generated/nb"

[nl]
  label = "Dutch"
  contentDir = "generated/nl"

[oc]
  label = "Occitan"
  contentDir = "generated/oc"

[pl]
  label = "Polish"
  contentDir = "generated/pl"

[pt]
  label = "Portuguese"
  contentDir = "generated/pt"

[pt_BR]
  label = "Portuguese (Brazilian)"
  locale = "pt-BR"
  contentDir = "generated/pt_BR"

[ro]
  label = "Romanian"
  contentDir = "generated/ro"

[ru]
  label = "Russian"
  contentDir = "generated/ru"

[sk]
  label = "Slovak"
  contentDir = "generated/sk"

[sl]
  label = "Slovenian"
  contentDir = "generated/sl"

[sq]
  label = "Albanian"
  contentDir = "generated/sq"

[sr]
  label = "Serbian"
  contentDir = "generated/sr"

[sv]
  label = "Swedish"
  contentDir = "generated/sv"

[th]
  label = "Thai"
  contentDir = "generated/th"

[tr]
  label = "Turkish"
  contentDir = "generated/tr"

[uk]
  label = "Ukrainian"
  contentDir = "generated/uk"

[vi]
  label = "Vietnamese"
  contentDir = "generated/vi"

[zh_CN]
  label = "Chinese (Simplified)"
  locale = "zh-CN"
  contentDir = "generated/zh_CN"

[zh_TW]
  label = "Chinese (Traditional)"
  locale = "zh-TW"
  contentDir = "generated/zh_TW"
