[en]
  label = "English"
  weight = 1
  contentDir = "content"

[ar]
  label = "Arabic"
  weight = 2
  contentDir = "content"

[bg]
  label = "Bulgarian"
  weight = 3
  contentDir = "content"

[ca]
  label = "Catalan"
  weight = 4
  contentDir = "content"

[cs]
  label = "Czech"
  weight = 5
  contentDir = "content"

[da]
  label = "Danish"
  weight = 6
  contentDir = "content"

[de]
  label = "German"
  weight = 7
  contentDir = "content"

[el]
  label = "Greek"
  weight = 8
  contentDir = "content"

[en-AU]
  label = "English (Australia)"
  weight = 9
  contentDir = "content"

[en-GB]
  label = "English (United Kingdom)"
  weight = 10
  contentDir = "content"

[es]
  label = "Spanish (Castilian)"
  weight = 11
  contentDir = "content"

[fa-IR]
  label = "Persian"
  weight = 12
  contentDir = "content"

[fr]
  label = "French"
  weight = 13
  contentDir = "content"

[gl]
  label = "Galician"
  weight = 14
  contentDir = "content"

[he]
  label = "Hebrew"
  weight = 15
  contentDir = "content"

[hu]
  label = "Hungarian"
  weight = 16
  contentDir = "content"

[id]
  label = "Indonesian"
  weight = 17
  contentDir = "content"

[it]
  label = "Italian"
  weight = 18
  contentDir = "content"

[ja]
  label = "Japanese"
  weight = 19
  contentDir = "content"

[kk]
  label = "Kazakh"
  weight = 20
  contentDir = "content"

[ko]
  label = "Korean"
  weight = 21
  contentDir = "content"

[lt]
  label = "Lithuanian"
  weight = 22
  contentDir = "content"

[ms]
  label = "Malay"
  weight = 23
  contentDir = "content"

[nb]
  label = "Norwegian Bokmal"
  weight = 24
  contentDir = "content"

[nl]
  label = "Dutch"
  weight = 25
  contentDir = "content"

[oc]
  label = "Occitan"
  weight = 26
  contentDir = "content"

[pl]
  label = "Polish"
  weight = 27
  contentDir = "content"

[pt]
  label = "Portuguese"
  weight = 28
  contentDir = "content"

[pt-BR]
  label = "Portuguese (Brazilian)"
  weight = 29
  contentDir = "content"

[ro]
  label = "Romanian"
  weight = 30
  contentDir = "content"

[ru]
  label = "Russian"
  weight = 31
  contentDir = "content"

[sk]
  label = "Slovak"
  weight = 32
  contentDir = "content"

[sl]
  label = "Slovenian"
  weight = 33
  contentDir = "content"

[sq]
  label = "Albanian"
  weight = 34
  contentDir = "content"

[sr]
  label = "Serbian"
  weight = 35
  contentDir = "content"

[sv]
  label = "Swedish"
  weight = 36
  contentDir = "content"

[th]
  label = "Thai"
  weight = 37
  contentDir = "content"

[tr]
  label = "Turkish"
  weight = 38
  contentDir = "content"

[uk]
  label = "Ukrainian"
  weight = 39
  contentDir = "content"

[vi]
  label = "Vietnamese"
  weight = 40
  contentDir = "content"

[zh-CN]
  label = "Chinese (Simplified)"
  weight = 41
  contentDir = "content"

[zh-TW]
  label = "Chinese (Traditional)"
  weight = 42
  contentDir = "content"
