defaultContentLanguage = "en"

[i18n]
  package = "xfce-www"
  # UI strings in i18n/en.json belong to the default domain -> po/ui.pot
  defaultDomain = "ui"
  reportAddress = "https://gitlab.xfce.org/websites/www.xfce.org/-/issues"
  srcDir = "content"
  genDir = "generated"
  genToOtherDir = true
  excludedKeys = "layout hasToc date titleKey"

  [i18n.others]
    strings = true

  [i18n.content]
    # markdown pages -> po/content.pot
    [i18n.content.content]
      globs = [
        "content/_index.md",
        "content/about/_index.md",
        "content/about/news/[0-9]*.md",
        "content/about/tour*.md",
        "content/community/_index.md",
        "content/download/_index.md",
        "content/download/changelogs/_index.md",
        "content/getinvolved/_index.md",
        "content/projects/_index.md",
      ]
