<?php

/**
 * This file is generated by the compile.sh script.
 * Do not modify it by hand!
 **/

/* known languages in this directory */
$languages = array (
	'en' => 'English');

/* used in header and language detection functions */
$language_codes = array_keys ($languages);
?>
