<?php

/* This file has been generated automatically. */

$translators_stamp = "2015-06-24 05:31:31 UTC";

$translators = array (
  'Albanian [sq]' => array (
    'Ard1t' => 'ardit'.DOTSIGN.'dani'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Besnik Bleta' => 'besnik'.ATSIGN.'programeshqip'.DOTSIGN.'org',
    'Erlin Hysenbelliu' => 'erlinh91'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Amharic [am]' => array (
    'Belay' => 'belaytekalign'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Tegegne Tefera' => 'tefera'.ATSIGN.'mekuria'.DOTSIGN.'com',
  ),
  'Arabic [ar]' => array (
    'عبدالله رضوان' => 'abbodmar'.ATSIGN.'gmail'.DOTSIGN.'com',
    'كريم أولاد الشلحة' => 'herr'.DOTSIGN.'linux88'.ATSIGN.'gmail'.DOTSIGN.'com',
    'abdXelrhman' => 'abdxelrhman'.ATSIGN.'gmail'.DOTSIGN.'com',
    'محمد الحرقان' => 'malham1'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ahmadzxc' => 'ahmad'.DOTSIGN.'almomani5'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Amine' => 'amine'.ATSIGN.'linuxac'.DOTSIGN.'org',
    'M. Fawwaz Orabi' => 'mfawwaz93'.ATSIGN.'gmail'.DOTSIGN.'com',
    'M.hanny Sabbagh' => 'hannysabbagh'.ATSIGN.'hotmail'.DOTSIGN.'com',
    'Mohsen' => 'linuxer9'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Noureddin Khatat' => 'noureddin'.ATSIGN.'barid'.DOTSIGN.'com',
    'Simohamed' => 'mohamed'.DOTSIGN.'sakhri'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Asturian [ast]' => array (
    'Enolp' => 'enolp'.ATSIGN.'softastur'.DOTSIGN.'org',
    'Iñigo Varela' => 'malditoastur'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Tornes Llume' => 'l'.DOTSIGN.'lumex03'.DOTSIGN.'tornes'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Basque [eu]' => array (
    'Asier Iturralde Sarasola' => 'asier'.DOTSIGN.'iturralde'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Piarres Beobide' => 'pi'.ATSIGN.'beobide'.DOTSIGN.'net',
  ),
  'Belarusian [be]' => array (
    'Andrei Zakharevich' => 'andrej'.ATSIGN.'zahar'.DOTSIGN.'ws',
    'Mikalai Udodau' => 'crom-a'.ATSIGN.'tut'.DOTSIGN.'by',
    'Mike Gelfand' => 'mikedld'.ATSIGN.'mikedld'.DOTSIGN.'com',
  ),
  'Bengali [bn]' => array (
    'Jamil Ahmed' => 'itsjamil'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Bulgarian [bg]' => array (
    'Gazarrr' => 'gazarrr'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Georgi Georgiev' => 'georgiev_1994'.ATSIGN.'abv'.DOTSIGN.'bg',
    'Kiril Kirilov' => 'cybercop_montana'.ATSIGN.'abv'.DOTSIGN.'bg',
    'Krasimir Chonov' => 'mk2616'.ATSIGN.'abv'.DOTSIGN.'bg',
    'Milen Milev' => 'fanfolet'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Valentin Tunev' => 'hdbuster'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Catalan [ca]' => array (
    'Alavios' => 'registres'.ATSIGN.'lavios'.DOTSIGN.'cat',
    'Carles Muñoz Gorriz' => 'carlesmu'.ATSIGN.'internautas'.DOTSIGN.'org',
    'Frangor' => 'frangor'.ATSIGN.'frangor'.DOTSIGN.'info',
    'Harald Servat' => 'redcrash'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Joan Montané' => 'joan'.ATSIGN.'montane'.DOTSIGN.'cat',
    'Lebrush' => 'lebrush'.ATSIGN.'xplosio'.DOTSIGN.'net',
    'Paul Garden' => 'kiari62'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Roger Pueyo Centelles' => 'xfce'.ATSIGN.'rogerpueyo'.DOTSIGN.'com',
    'Sandandmercury' => 'sandandmercury'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Chinese (China) [zh_CN]' => array (
    'Chipong Luo' => 'chipong'.DOTSIGN.'luo'.ATSIGN.'yahoo'.DOTSIGN.'com',
    'Greensea' => 'gs'.ATSIGN.'bbxy'.DOTSIGN.'net',
    'Hunt Xu' => 'mhuntxu'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Qianqian Fang' => 'fangqq'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Xianhao' => 'qinghao1'.ATSIGN.'foxmail'.DOTSIGN.'com',
    '玉堂白鹤' => 'yjwork'.ATSIGN.'qq'.DOTSIGN.'com',
    '周潇波' => 'zhouxiaobo'.DOTSIGN.'500'.ATSIGN.'gmail'.DOTSIGN.'com',
    '白铭骢' => 'jeffbaichina'.ATSIGN.'members'.DOTSIGN.'fsf'.DOTSIGN.'org',
  ),
  'Chinese (Hong Kong) [zh_HK]' => array (
    'Walter Cheuk' => 'wwycheuk'.ATSIGN.'gmail'.DOTSIGN.'com',
    '文豪 卫' => 'waimanho2765galois'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Chinese (Taiwan) [zh_TW]' => array (
    'Cheng-Chia Tseng' => 'pswo10680'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Chia-Han Lee' => 'gloomysaga'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ethan42411' => 'jrpropo10282003'.ATSIGN.'yahoo'.DOTSIGN.'com'.DOTSIGN.'tw',
    'Jeff Huang' => 's8321414'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pei Yi Chen' => 'cpyimail'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ruei-Yuan Lu' => 'rueiyuan'.DOTSIGN.'lu'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sofyalai' => 'sofyalai'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Walter Cheuk' => 'wwycheuk'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Croatian [hr]' => array (
    'Denis Štogl' => 'denisstogl'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Edin Veskovic' => 'edin'.DOTSIGN.'veskovic'.ATSIGN.'openmailbox'.DOTSIGN.'org',
    'Ivica  Kolić' => 'ikoli'.ATSIGN.'yahoo'.DOTSIGN.'com',
    'Petar Koretić' => 'petar'.DOTSIGN.'koretic'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Czech [cs]' => array (
    'Alois Nešpor' => 'info'.ATSIGN.'aloisnespor'.DOTSIGN.'info',
    'Franti3ek' => 'frantisek'.DOTSIGN.'komarek'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Fri' => 'pavelfric'.ATSIGN.'seznam'.DOTSIGN.'cz',
    'Libor Schejbal' => 'libor'.DOTSIGN.'schejbal'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Michal Várady' => 'miko'.DOTSIGN.'vaji'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Per Kongstad' => 'p_kongstad'.ATSIGN.'op'.DOTSIGN.'pl',
    'Radim Kolář' => 'kolar'.DOTSIGN.'radim'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Robert Hartl' => 'hartl'.DOTSIGN.'robert'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Danish [da]' => array (
    'Aputsiaĸ Niels Janussen' => 'aj'.ATSIGN.'isit'.DOTSIGN.'gl',
    'Chris Darnell' => 'chris'.ATSIGN.'cedeel'.DOTSIGN.'com',
    'Erik Schmidt' => 'erischmi'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kris Thomsen' => 'lakristho'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Morten Juhl-Johansen Zölde-Fejér' => 'mjjzf'.ATSIGN.'syntaktisk'.DOTSIGN.'dk',
    'Per Kongstad' => 'p_kongstad'.ATSIGN.'op'.DOTSIGN.'pl',
  ),
  'Dutch (Flemish) [nl]' => array (
    'Auke Kok' => 'sofar'.ATSIGN.'foo-projects'.DOTSIGN.'org',
    'Nick Schermer' => 'nickschermer'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pjotr Anon' => 'pliniusminor'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pjotr Vertaalt' => 'pjotrvertaalt'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Timo Verbeek' => 'timoverbeek10'.ATSIGN.'hotmail'.DOTSIGN.'com',
    'Vincent Tunru' => 'projects'.ATSIGN.'vinnl'.DOTSIGN.'nl',
  ),
  'English (Australia) [en_AU]' => array (
    'Michael Findlay' => 'keltoiboy'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'English (Great Britain) [en_GB]' => array (
    'Jeff Bailes' => 'thepizzaking'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Noskcaj' => 'noskcaj'.ATSIGN.'ubuntu'.DOTSIGN.'com',
    'Readmanr' => 'robert_readman'.ATSIGN.'hotmail'.DOTSIGN.'com',
  ),
  'Esperanto [eo]' => array (
    'Aleksandr Ponomarenko' => 'davian818'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Edsono' => 'edsono'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Estonian [et]' => array (
    'Allar Kiristaja' => 'aquastus'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mattias Põldaru' => 'mahfiaz'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Finnish [fi]' => array (
    'Flammie Pirinen' => 'flammie'.ATSIGN.'iki'.DOTSIGN.'fi',
    'Jari Rahkonen' => 'jari'.DOTSIGN.'rahkonen'.ATSIGN.'pp1'.DOTSIGN.'inet'.DOTSIGN.'fi',
    'Jarno Liimatainen' => 'jarliim'.ATSIGN.'iki'.DOTSIGN.'fi',
    'Jiri Grönroos' => 'jiri'.DOTSIGN.'gronroos'.ATSIGN.'iki'.DOTSIGN.'fi',
    'Juhani Numminen' => 'juhaninumminen0'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Lasse Liehu' => 'larso'.ATSIGN.'gmx'.DOTSIGN.'com',
    'Pasi Lallinaho' => 'pasi'.ATSIGN.'shimmerproject'.DOTSIGN.'org',
    'Tapio Väisänen' => 'tapio'.DOTSIGN.'vaeisaenen'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Tero Mononen' => 'tero'.ATSIGN.'mononen'.DOTSIGN.'eu',
  ),
  'French [fr]' => array (
    'Anthony Jorion' => 'pingax'.ATSIGN.'frugalware'.DOTSIGN.'fr',
    'Benoit Thibaud' => 'frombenny'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Douart Patrick' => 'patrick'.DOTSIGN.'2'.ATSIGN.'laposte'.DOTSIGN.'net',
    'Durand-Favreau Arnaud' => 'biginoz'.ATSIGN.'free'.DOTSIGN.'fr',
    'Fevrier' => 'jean-philippe'.DOTSIGN.'guerard'.ATSIGN.'tigreraye'.DOTSIGN.'org',
    'Filorin' => 'guillaume'.DOTSIGN.'ber17'.ATSIGN.'laposte'.DOTSIGN.'net',
    'Glaville' => 'laville'.DOTSIGN.'guillaume'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Iliyas Jorio' => 'inv'.DOTSIGN.'jorio'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Jc Jc1' => 'jc1'.DOTSIGN.'quebecos'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Jean-Philippe Fleury' => 'contact'.ATSIGN.'jpfleury'.DOTSIGN.'net',
    'Jérôme Guelfucci' => 'jeromeg'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Louis Moureaux' => 'm_louis30'.ATSIGN.'yahoo'.DOTSIGN.'com',
    'Mario Gervais' => 'gervais'.DOTSIGN.'mario'.ATSIGN.'ymail'.DOTSIGN.'com',
    'Maximilian Schleiss' => 'maximilian'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Mike Massonnet' => 'mmassonnet'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Nodiscc' => 'nodiscc'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pedwo51' => 'pedwo51'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pierre Albiero' => 'trepalum'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pingax' => 'pingax'.ATSIGN.'frugalware'.DOTSIGN.'org',
    'Remi Andruccioli' => 'remi'.DOTSIGN.'andruccioli'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Steve Dodier' => 'sidnioulz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Urien Desterres' => 'urien'.DOTSIGN.'desterres'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Xavier Devlamynck' => 'magicrhesus'.ATSIGN.'ouranos'.DOTSIGN.'be',
    'Yannick Le Guen' => 'leguen'.DOTSIGN.'yannick'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Galician [gl]' => array (
    'Dani Mf' => 'dani'.ATSIGN.'damufo'.DOTSIGN.'com',
    'Leandro Regueiro' => 'leandro'.DOTSIGN.'regueiro'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'German [de]' => array (
    'Chris Leick' => 'c'.DOTSIGN.'leick'.ATSIGN.'vollbio'.DOTSIGN.'de',
    'Christoph Mende' => 'angelos'.ATSIGN.'gentoo'.DOTSIGN.'org',
    'Christoph Wickert' => 'christoph'.DOTSIGN.'wickert'.ATSIGN.'googlemail'.DOTSIGN.'com',
    'David Mohr' => 'david'.ATSIGN.'mcbf'.DOTSIGN.'net',
    'Detlef Riekenberg' => 'wine'.DOTSIGN.'dev'.ATSIGN.'web'.DOTSIGN.'de',
    'Fabian Nowak' => 'timystery'.ATSIGN.'arcor'.DOTSIGN.'de',
    'Georg Eckert' => 'eckert'.DOTSIGN.'georg'.ATSIGN.'gmx'.DOTSIGN.'de',
    'Harald Judt' => 'h'.DOTSIGN.'judt'.ATSIGN.'gmx'.DOTSIGN.'at',
    'Jakob Kramer' => 'jakob'.DOTSIGN.'kramer'.ATSIGN.'gmx'.DOTSIGN.'de',
    'Jannis Pohlmann' => 'jannis'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Johannes Lips' => 'johannes'.DOTSIGN.'lips'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mario Blättermann' => 'mario'.DOTSIGN.'blaettermann'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mark Trompell' => 'mark'.ATSIGN.'foresightlinux'.DOTSIGN.'org',
    'Michael Spahn' => 'any0n3'.ATSIGN.'fedoraproject'.DOTSIGN.'org',
    'Paul Seyfert' => 'pseyfert'.ATSIGN.'mathphys'.DOTSIGN.'fsk'.DOTSIGN.'uni-heidelberg'.DOTSIGN.'de',
    'Raphael Groner' => 'raphgro'.ATSIGN.'web'.DOTSIGN.'de',
    'Roland Kübert' => 'roland'.ATSIGN.'upic'.DOTSIGN.'de',
    'Simon Steinbeiss' => 'ochosi'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Thomas Schütz' => 'xfce'.ATSIGN.'thschuetz'.DOTSIGN.'de',
    'Tobias Bannert' => 'tobannert'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Uwe Krause' => 'derhorst'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Greek [el]' => array (
    'Efstathios Iosifidis' => 'iefstathios'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Evaggelos Balaskas' => 'ebalaskas'.ATSIGN.'ebalaskas'.DOTSIGN.'gr',
    'Forfolias' => 'forfolias'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gapan' => 'vlahavas'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Georgios Stefanakis' => 'nonviotale'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Jani Kotsionis' => 'ikotsionis'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Klearchos-Angelos Gkountras' => 'kleagkou'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Loathingkernel' => 'zeronebones'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Madits' => 'dimitsas'.DOTSIGN.'markos'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mario Andonoudiou' => 'supermodmusic'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Spiros Georgaras' => 'sng'.ATSIGN.'hellug'.DOTSIGN.'gr',
    'Spyros' => 'spyros_stravoravdis'.ATSIGN.'hotmail'.DOTSIGN.'com',
    'Stavros Giannouris' => 'stavrosg'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Hebrew [he]' => array (
    'GenghisKhan' => 'genghiskhan'.ATSIGN.'gmx'.DOTSIGN.'ca',
    'Hezy Amiel' => 'open'.ATSIGN.'hezyamiel'.DOTSIGN.'com',
    'Nick Vurgaft' => 'slipperygate'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Yaron Shahrabani' => 'sh'.DOTSIGN.'yaron'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Hungarian [hu]' => array (
    'Gabor Kelemen' => 'kelemeng'.ATSIGN.'gnome'.DOTSIGN.'hu',
    'Gyönki Bendegúz' => 'gyonkibendeguz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Imre Benedek' => 'nucleo'.ATSIGN.'indamail'.DOTSIGN.'hu',
    'Kelemeng' => 'kelemeng'.ATSIGN.'ubuntu'.DOTSIGN.'com',
    'László Horváth' => 'leslie'.DOTSIGN.'translate'.ATSIGN.'yahoo'.DOTSIGN.'co'.DOTSIGN.'uk',
    'Nagy Gábor' => 'jackson'.DOTSIGN.'gabor'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Icelandic [is]' => array (
    'Kristófer Arnþórsson' => 'kristoferarnthors'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sveinn í Felli' => 'sveinki'.ATSIGN.'nett'.DOTSIGN.'is',
    'Theódór S. Andrésson' => 'husgafl'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Indonesian [id]' => array (
    'Andhika Padmawan' => 'andhika'.DOTSIGN.'padmawan'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ardjuna' => 'asyura'.DOTSIGN.'x'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Rendiyono Wahyu Saputro' => 'rendi'.DOTSIGN.'7936'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Zaenal' => 'zaenal1234'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Italian [it]' => array (
    'Amigamagic' => 'debianmaverick'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Andreazube' => 'andreazuben'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Crazyaxe' => 'angerangel'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Cristian Marchi' => 'cri'.DOTSIGN.'penta'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Edoardo Maria Elidoro' => 'edoardo'.DOTSIGN.'elidoro'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Enrico Polesel' => 'polesel'.ATSIGN.'poisson'.DOTSIGN.'phc'.DOTSIGN.'unipi'.DOTSIGN.'it',
    'Francesco Galizzi' => 'f'.DOTSIGN.'galizzi92'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Francesco Groccia' => 'frgroccia'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gianluca Foddis' => 'gianluca'.DOTSIGN.'foddis'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Leonardo Totaro' => 'elleti'.DOTSIGN.'brainvision'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Milozzy' => 'marco'.DOTSIGN.'sting'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Salvatorexfce' => 'salvatorexfce'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Winebar' => 'vs'.DOTSIGN.'winebar'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Japanese [ja]' => array (
    'Hchenmisc' => 'hao'.DOTSIGN.'chen'.DOTSIGN.'jobs'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Masato Hashimoto' => 'hashimo'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Nobuhiro Iwamatsu' => 'iwamatsu'.ATSIGN.'nigauri'.DOTSIGN.'org',
  ),
  'Kazakh [kk]' => array (
    'Baurzhan Muftakhidinov' => 'baurthefirst'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Korean [ko]' => array (
    'BAK Chan-Jin' => 'yeoulongg'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Jasonjang' => 'hl1sxa'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kentarch' => 'bkrhlim'.ATSIGN.'aol'.DOTSIGN.'com',
    'Lego37yoon' => 'lego37yoon'.ATSIGN.'outlook'.DOTSIGN.'com',
    'Seong-ho Cho' => 'darkcircle'.DOTSIGN.'0426'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sungjin Gang' => 'potopro'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sung Jin Gang' => 'ujuc'.ATSIGN.'ujuc'.DOTSIGN.'kr',
  ),
  'Latvian [lv]' => array (
    'Gatis Kalniņš <> <Gatis Kalniņš' => '>',
    'Rihards Prieditis' => 'rprieditis'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Lithuanian [lt]' => array (
    'Algimantas Margevičius' => 'margevicius'.DOTSIGN.'algimantas'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ričardas Vasiulis' => 'ricardas'.DOTSIGN.'v'.ATSIGN.'inbox'.DOTSIGN.'lt',
  ),
  'Malay [ms]' => array (
    'Abuyop' => 'abuyop'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ceghap' => 'hello'.ATSIGN.'ceghap'.DOTSIGN.'com',
    'Mohd. Nadzrin Sapari' => 'terjemah'.DOTSIGN.'puretech'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Norwegian Bokmål [nb]' => array (
    'Allan Nordhøy' => 'epost'.ATSIGN.'anotheragency'.DOTSIGN.'no',
    'Haarek' => 'haarektrans'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kevin Brubeck Unhammer' => 'javkalas'.ATSIGN.'mm'.DOTSIGN.'st',
    'Papparonny' => 'ronny'.ATSIGN.'olufsen'.DOTSIGN.'org',
    'Takoi' => 'thomas'.DOTSIGN.'amland'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Terje Uriansrud' => 'terje'.ATSIGN.'uriansrud'.DOTSIGN.'net',
  ),
  'Norwegian Nynorsk [nn]' => array (
    'Eivind Ødegård' => 'gingermig'.ATSIGN.'yahoo'.DOTSIGN.'no',
    'Håvard Krogstie' => 'krogstie'.DOTSIGN.'havard'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kevin Brubeck Unhammer' => 'javkalas'.ATSIGN.'mm'.DOTSIGN.'st',
  ),
  'Occitan [oc]' => array (
    'Cedric31' => 'cvalmary'.ATSIGN.'yahoo'.DOTSIGN.'fr',
  ),
  'Panjabi [pa]' => array (
    'A S Alam' => 'apreet'.DOTSIGN.'alam'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Persian [fa]' => array (
    'Mehdi Esmaeelpour' => 'ariarat'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Polish [pl]' => array (
    'Adam Stachowicz' => 'saibamenppl'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Cyryl Sochacki' => 'cyrylsochacki'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Dawid' => 'hoek'.ATSIGN.'hoek'.DOTSIGN.'pl',
    'Elder' => 'elderlinx'.ATSIGN.'riseup'.DOTSIGN.'net',
    'Elzear' => 'babciaroziazpogwizdowa'.ATSIGN.'wp'.DOTSIGN.'pl',
    'Emanuel Borówko' => 'trzynastak'.ATSIGN.'o2'.DOTSIGN.'pl',
    'Ireneusz Gierlach' => 'irek'.DOTSIGN.'gierlach'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Jakub Waśko' => 'javazlaz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kamil Polczak' => 'elderlinx'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Marcin Romańczuk' => 'abjsyn'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Michał Jeż' => 'michal'.DOTSIGN.'je2u'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Michał Olber' => 'michal'.DOTSIGN.'olber'.ATSIGN.'osworld'.DOTSIGN.'pl',
    'Paweł Bandura' => 'gawelx'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pawel10' => 'pawelklimek102'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Piotr Sokół' => 'psokol'.ATSIGN.'jabster'.DOTSIGN.'pl',
    'Piotr Strębski' => 'strebski'.ATSIGN.'o2'.DOTSIGN.'pl',
    'Tomasz Chudyk' => 'chudyk'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Portuguese [pt]' => array (
    'Alexandre Fidalgo' => 'alexandremagnos15'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Nuno Miguel' => 'nunomgue'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sérgio Marques' => 'smarquespt'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Portuguese (Brazilian) [pt_BR]' => array (
    'André Miranda' => 'andreldm1989'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Cleber de Souza Corrêa' => 'cscorrea'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Enrico Nicoletto' => 'enrico'.DOTSIGN.'br'.ATSIGN.'gmx'.DOTSIGN.'co'.DOTSIGN.'uk',
    'Henrique P. Machado' => 'zehrique'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Joelso Andrade' => 'kosmofilo'.ATSIGN.'ymail'.DOTSIGN.'com',
    'Michael Martins' => 'michaelfm21'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Miguel Frasson' => 'mvsfrasson'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mtobias' => 'marcelo'.DOTSIGN.'tobbias'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Neliton Pereira Junior' => 'nelitonpjr'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Og Maciel' => 'ogmaciel'.ATSIGN.'gnome'.DOTSIGN.'org',
    'Rafael Ferreira' => 'rafael'.DOTSIGN.'f'.DOTSIGN.'f1'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Rafael Neri' => 'rafepel'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sérgio Cipolla' => 'secipolla'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Tomas Schertel' => 'tschertel'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Victor Gonçalves' => 'hotcyv'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Vladimir Melo' => 'vladimirmelo'.DOTSIGN.'psi'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Romanian [ro]' => array (
    'Mișu Moldovan' => 'dumol'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Strainu' => 'xfce'.ATSIGN.'strainu'.DOTSIGN.'ro',
  ),
  'Russian [ru]' => array (
    '026rus' => '026rus'.ATSIGN.'gmail'.DOTSIGN.'com',
    'AK' => 'ak099'.ATSIGN.'mail'.DOTSIGN.'ru',
    'Aleksandr Ponomarenko' => 'davian818'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Aleksandr Sorokin' => 'equusa'.ATSIGN.'gmail'.DOTSIGN.'com',
    'AlexanderFilev' => 'ifillrok'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Alexander Matveyev' => 'a'.DOTSIGN.'s'.DOTSIGN.'matveyev'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Alexandr Boltris' => 'ua2fgb'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Alexey Batiuk' => 'alexey'.DOTSIGN.'batiuk'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Alex Z' => 'ad_user'.ATSIGN.'lavabit'.DOTSIGN.'com',
    'Andres Kovtunos' => 'kovtunos'.ATSIGN.'yandex'.DOTSIGN.'ru',
    'Andrey Ivankov' => 'andrey'.DOTSIGN.'ivankov'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Artem Zolochevskiy' => 'artem'.DOTSIGN.'zolochevskiy'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Brdassign' => 'dmitriy'.DOTSIGN.'borodiy'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Claque' => 'cpt-alatriste'.ATSIGN.'ya'.DOTSIGN.'ru',
    'Denis Koryavov' => 'dkoryavov'.ATSIGN.'yandex'.DOTSIGN.'ru',
    'Dmitrij Smirnov' => 'arch'.ATSIGN.'cnc-parts'.DOTSIGN.'info',
    'Dmitriy Kudryashov' => 'overmailed'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kyrill Detinov' => 'lazy'.DOTSIGN.'kent'.ATSIGN.'opensuse'.DOTSIGN.'org',
    'Lowrider' => 'pams'.ATSIGN.'imail'.DOTSIGN.'ru',
    'Roman K' => 'mrdoctorwho'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergey Alyoshin' => 'alyoshin'.DOTSIGN.'s'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergey Shlyapugin' => 'shlyapugin'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Someniatko' => 'someniatko'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Styopa Semenukha' => 'semenukha'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Velisarus' => 'velisarus'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Vlad Vasilev' => 'lortwer'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Serbian [sr]' => array (
    'Мирослав Николић' => 'miroslavnikolic'.ATSIGN.'rocketmail'.DOTSIGN.'com',
    'Саша Петровић' => 'salepetronije'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Harald Judt' => 'h'.DOTSIGN.'judt'.ATSIGN.'gmx'.DOTSIGN.'at',
    'Mpopovic' => 'gpopac'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Sinhala [si]' => array (
    'Akila Wajirasena' => 'akila'.DOTSIGN.'wajirasena'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Anandawardhana' => 'anandawardhana'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Danishka Navin' => 'danishka'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kalpa Pathum Welivitigoda' => 'callkalpa'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kasundigital' => 'kasunindika'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kpgtharaka' => 'kpgtharaka'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Prabath Galagamage' => 'gprabath'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Slovak [sk]' => array (
    'Marek Hlava' => 'headsvk'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Michal Löffler' => 'lofflermichalloffler'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Peter Bubelíny' => 'p'.DOTSIGN.'bubeliny'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Robert Hartl' => 'hartl'.DOTSIGN.'robert'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Slavko' => 'linux'.ATSIGN.'slavino'.DOTSIGN.'sk',
    'Tomáš Vadina' => 'kyberdev'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Slovenian [sl]' => array (
    'Ansich' => 'mojmejlzaforume'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Anthonmanix' => 'anthon'.DOTSIGN.'manix'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Dražen M' => 'drazen'.ATSIGN.'ubuntu'.DOTSIGN.'si',
    'Gašper Tomažič' => 'gasper'.ATSIGN.'gmx'.DOTSIGN.'com',
    'Holden87' => 'latinovic87'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Klemen Košir' => 'klemen913'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Nenad Latinović' => 'nenadlatinovic'.ATSIGN.'lavabit'.DOTSIGN.'com',
    'Rok Kepa' => 'rokkepa'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sasa Batistic' => 'sasa'.DOTSIGN.'batistic'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Uros Preloznik' => 'uros00'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Spanish [es]' => array (
    'Abel Martín' => 'abel'.DOTSIGN.'martin'.DOTSIGN.'ruiz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Adolfo Jayme Barrientos' => 'fitoschido'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Andres Sanchez' => 'afsanchez93'.ATSIGN.'gmail'.DOTSIGN.'com',
    'César Enrique García' => 'cquike'.ATSIGN.'gmail'.DOTSIGN.'com',
    'David Segura Monroy' => 'davidseg'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Edwinpm5' => 'edwinpm5'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Francisco Javier Serrador' => 'fserrador'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Franco Tortoriello' => 'torto09'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gabrieltandil' => 'gabriel'.DOTSIGN.'tandil'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gonzalo Lagos' => 'xalo'.DOTSIGN.'em'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Hernan Gabriel Alvarez Guerra' => 'hernan'.DOTSIGN.'alvarez'.DOTSIGN.'guerra'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ignacio Velasco' => 'elega'.ATSIGN.'elega'.DOTSIGN.'com'.DOTSIGN.'ar',
    'Javier Sánchez Reinosa' => 'donoban'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Lbazan' => 'bazanluis20'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Manolo Díaz' => 'diaz'.DOTSIGN.'manolo'.ATSIGN.'gmail'.DOTSIGN.'com',
    'MC' => 'correomc2000-ing'.ATSIGN.'yahoo'.DOTSIGN.'es',
    'Pablo Lezaeta' => 'prflr88'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Pharamir' => 'pamirmatos'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergio García' => 'oigres200'.ATSIGN.'gmail'.DOTSIGN.'com',
    'The Idiot' => 'brian'.DOTSIGN.'peraza'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Swedish [sv]' => array (
    'Alex Nordlund' => 'deep'.DOTSIGN.'alexander'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Bittin' => 'cs_bittin'.ATSIGN.'msn'.DOTSIGN.'com',
    'Daniel Nylander' => 'po'.ATSIGN.'danielnylander'.DOTSIGN.'se',
    'Elefterios Lundell' => 'winnie666'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Fredrik Nyqvist' => 'fredrik'.ATSIGN.'nyqvist'.DOTSIGN.'biz',
    'Kim Svensson' => 'ks6g10'.ATSIGN.'soton'.DOTSIGN.'ac'.DOTSIGN.'uk',
    'Peterdenk' => 'peter'.ATSIGN.'skypay'.DOTSIGN.'se',
    'Påvel Nicklasson' => 'pavelnicklasson'.ATSIGN.'bahnhof'.DOTSIGN.'se',
    'Rickard Larsson' => 'larsson'.ATSIGN.'odus'.DOTSIGN.'se',
  ),
  'Telugu [te]' => array (
    'వీవెన్' => 'veeven'.ATSIGN.'gmail'.DOTSIGN.'com',
    'ప్రవీణ్ ఇళ్ళ' => 'mail2ipn'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Thai [th]' => array (
    'Theppitak Karoonboonyanan' => 'theppitak'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Turkish [tr]' => array (
    'Akın Ömeroğlu' => 'akin'.ATSIGN.'pardus'.DOTSIGN.'org'.DOTSIGN.'tr',
    'Ali Polatel' => 'ali'.DOTSIGN.'polatel'.ATSIGN.'ozguryazilim'.DOTSIGN.'com'.DOTSIGN.'tr',
    'Alper Tekinalp' => 'alper'.DOTSIGN.'tekinalp'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Askar05' => 'asirkaraman'.ATSIGN.'yahoo'.DOTSIGN.'de',
    'Aybuke' => 'aybuke'.DOTSIGN.'147'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Aydan Taşdemir' => 'aydantasdemir'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ayhan YALÇINSOY' => 'ayhanyalcinsoy'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Caner Gural' => 'cgural'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ertuğrul HAZAR' => 'ertugrulhazar'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Farukuzun' => 'farukuzun'.ATSIGN.'mail'.DOTSIGN.'com',
    'Fatih Erdem' => '93'.DOTSIGN.'fatiherdem'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gökhan Kılınç' => 'kilincgokhan'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gökmen Görgen' => 'gkmngrgn'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ilker Dagli' => 'ilker'.ATSIGN.'ilkerdagli'.DOTSIGN.'info',
    'Martinamca' => 'martinamca'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mustafa Tekkoyun' => 'mustafa'.DOTSIGN.'tekkoyun'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Natavan Mirzayeva' => 'mirzayevanatavan'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Necdet Yücel' => 'necdetyucel'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Osman Karagöz' => 'osmank3'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Samed Beyribey' => 'beyribey'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Server Acim' => 'serveracim'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Utku Aydın' => 'utkuaydin'.ATSIGN.'archlinux'.DOTSIGN.'org'.DOTSIGN.'tr',
    'Utku Berberoğlu' => 'utku'.DOTSIGN.'berber'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Volkangezer' => 'volkangezer'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Yakup' => 'mutouk'.ATSIGN.'yandex'.DOTSIGN.'ru',
    'Zafer Eren' => 'zaferern'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Zeki' => 'zeki'.DOTSIGN.'ozguryazilim'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Özgür Kuru' => 'ozgur'.ATSIGN.'ozgurkuru'.DOTSIGN.'net',
  ),
  'Ukrainian [uk]' => array (
    'Andriy Matkovsky' => 'sidius'.DOTSIGN.'ua'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Dmitry Nikitin' => 'luckas_fb'.ATSIGN.'mail'.DOTSIGN.'ru',
    'Oleksandr Natalenko' => 'pfactum'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Olexandr Nesterenko' => 'olexn'.ATSIGN.'ukr'.DOTSIGN.'net',
    'Pavlo Bilyak' => 'jpavlo11'.ATSIGN.'ukr'.DOTSIGN.'net',
    'Yarema aka Knedlyk' => 'yupadmin'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Zubr139' => 'zubr139'.ATSIGN.'ukr'.DOTSIGN.'net',
  ),
  'Uyghur [ug]' => array (
    'Abduqadir Abliz' => 'sahran'.DOTSIGN.'ug'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Gheyret Kenji' => 'gheyret'.ATSIGN.'yahoo'.DOTSIGN.'com',
  ),
  'Uzbek [uz]' => array (
    'Umidjon Almasov' => 'u'.DOTSIGN.'almasov'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Vietnamese [vi]' => array (
    'Crziter' => 'crziter'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Duy Truong Nguyen' => 'truongap'.DOTSIGN.'ars'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ppanhh' => 'ppanhh'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Vinh Nguyen' => 'kureikain'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
);
?>
