<?php

$translators_stamp = "2020-12-19 00:00:00 UTC";

$translators = array (
    "A7medicine",
    "Abduqadir Abliz",
    "abuyop",
    "acutbal",
    "Aestan",
    "AILTON ANDRADE LIMA",
    "Aitor Beriain",
    "Aleksey Kabanov",
    "Alexander Filev",
    "Alexandre Fidalgo",
    "Alfredo Natale",
    "Alfredo Quintero",
    "Ali Molaei",
    "Ali Rostami",
    "Aljoša Žagar",
    "Allan Nordhøy",
    "Andi Chandler",
    "Andrea Mura",
    "Andreas Eitel",
    "Andre Miranda",
    "Andrii Protsun",
    "Anonymous",
    "Apóstolos Papaðimitríu",
    "Aram Palyan",
    "Ardjuna",
    "Arianit Kukaj",
    "Arman Harutyunyan",
    "Arnold Marko",
    "Arve Eriksson",
    "Ashraful Islam",
    "Asier Iturralde Sarasola",
    "Åsmund Berg Holm",
    "bact",
    "Balázs Meskó",
    "Baurzhan Muftakhidinov",
    "bebabi34",
    "Ben",
    "Benedek Imre",
    "beriain",
    "Besnik",
    "Besnik Bleta",
    "Butterfly",
    "byStarTW (pan93412)",
    "Carlos Dz",
    "Cenk Yıldızlı",
    "César Enrique García",
    "Charles Monzat",
    "Chris Darnell",
    "Christian Manuel Torres Romero",
    "Christos Arvanitis",
    "cip",
    "clmmbs",
    "Cybertramp",
    "Dabid Martinez",
    "Daniel Muñiz Fontoira",
    "Davidmp",
    "Demiray Muhterem",
    "Demiray “tulliana” Muhterem",
    "Dmitri Bogomolov",
    "Dmytro Semenchenko",
    "Dongyu Chu",
    "dragnadh",
    "dsafsadf",
    "dull2wall",
    "Dumitru Moldovan",
    "Dušan Kazik",
    "Edin Veskovic",
    "Edoardo Maria Elidoro",
    "Efstathios Iosifidis",
    "Eirik Dekko",
    "Elishai Eliyahu",
    "Emanuele Petriglia",
    "emiliano casal chiarotti",
    "Emin Tufan",
    "enolp",
    "Enrico B",
    "Erlend Østlie",
    "filiperosset",
    "Francesco Galizzi",
    "Francisco",
    "Francisco F. Serrador",
    "František Jamrich",
    "Gatis Kalniņš",
    "Georg Eckert",
    "Georgi Georgiev",
    "Georgios Zarkadas",
    "Geraint Rowlands",
    "Goudarz Jafari",
    "Grzegorz Gębczyński",
    "Guillaume Laville",
    "Hamid Sarmadi",
    "Harald H",
    "Håvard Krogstie",
    "Hayk Andreasyan",
    "Héctor M. Monacci",
    "Hsiu-Ming Chang",
    "Hugo Carvalho",
    "Hüseyin Fahri Uzun",
    "idetao",
    "Ignacio Poggi",
    "Igor",
    "iman salmani",
    "Iris Ilexiris",
    "Îslam Zinar",
    "Ivailo Panamski",
    "Ivan",
    "Ivica  Kolić",
    "Jackson Doak",
    "Jakub Orsula",
    "Jason Collins",
    "Javier F. Serrador",
    "jc1",
    "Jeff Huang",
    "Jiri Grönroos",
    "Johannes Lips",
    "John Humphrys",
    "jolupa",
    "Jose Riha",
    "José Vieira",
    "Juhani Numminen",
    "박정규(Jung-Kyu Park)",
    "kdeguchi",
    "kelemeng",
    "Kevin Brubeck Unhammer",
    "Kiril Kirilov",
    "Kjell Cato Heskjestad",
    "Klemen Košir",
    "Knezev",
    "kozec",
    "Kukuh Syafaat",
    "Ldm Public",
    "Levi Zhou",
    "Linuxbruger",
    "Lowrider",
    "Lucas Wilm",
    "Luclu7",
    "Luis Borges",
    "Luis Mendoza",
    "Luna Jernberg",
    "Magnus Berg",
    "Marcelo Tobias",
    "Marcin Mikołajczak",
    "Mark",
    "Mark Lüthje",
    "Martin Stenröse",
    "Maxime Bonillo",
    "Michael Findlay",
    "Michael Martins",
    "Michał Olber",
    "Michal Pirchala",
    "Michal Várady",
    "Mingcong Bai",
    "mohammad alhargan",
    "Muhammet Kara",
    "Mustafa TEKKOYUN",
    "Nasser Bin Laboun",
    "Natavan Mirzayeva",
    "Necdet Yücel",
    "Nevzat Kılıçarslan",
    "Nguyên Bình",
    "Nick Schermer",
    "Nikola Radovanović",
    "Nobuhiro Iwamatsu",
    "nodiscc",
    "Nuno Miguel",
    "Oliver Burkardt",
    "Otavio Augusto Gomes",
    "Oukiki Saleh",
    "Panagiotis Mantzios",
    "Panwar108",
    "Pasi Lallinaho",
    "Pavel Borecki",
    "Påvel Nicklasson",
    "Piarres Beobide",
    "Piotr Sokół",
    "Pjotr",
    "prflr88",
    "Priit Jõerüüt",
    "Programy1 Programy1",
    "Rafael Fontenelle",
    "Real School",
    "Remi Andruccioli",
    "Rihards Skuja",
    "Robert Antoni Buj Gelonch",
    "Robert Readman",
    "Roger Pueyo Centelles",
    "Rox fr",
    "Rui",
    "Sajjad Sadeghi",
    "samson",
    "Samvel Harutyunyan",
    "Saroj Dhakal",
    "Saverio",
    "Seán Ó Séaghdha",
    "Seok Chae",
    "Seong-ho Cho",
    "Serdar Sağlam",
    "Sergey Alyoshin",
    "Shun",
    "Simon Steinbeiß",
    "Slavko",
    "Sr Aldeano",
    "Stefan Höök",
    "Steffen Trog",
    "Stephanos Papanikolopoulos",
    "Steve Harris",
    "Sveinn í Felli",
    "Sven Hillebrand",
    "tap saja",
    "Taufik Mulyana",
    "Tero Mononen",
    "Theppitak Karoonboonyanan",
    "Tobias Bannert",
    "Tomas",
    "Toni Estévez",
    "Triyan W. Nugroho",
    "T Tefera",
    "Urien Desterres",
    "user14",
    "UTUMI Hirosi",
    "vaba",
    "Vahe Safaryan",
    "Vasyl Khrystiuk",
    "Victor Gonçalves",
    "Viktor Odintsev",
    "Vincenzo Reale",
    "Vinzenz Vietzke",
    "vladi105",
    "Volkan Gezer",
    "vyper",
    "wakutiteo",
    "Walter Cheuk",
    "Warut Bunprasert",
    "Wellington Almeida",
    "wwj402",
    "Xavi G",
    "xiaobo zhou",
    "Xiaobo Zhou",
    "Xosé",
    "YAMADA Shinichirou",
    "Yannick Le Guen",
    "Yarema aka Knedlyk",
    "Yaşar Çiv",
    "YuHeng Chou",
    "zmicer turok",
    "Zmicer Turok",
    "zura davitashvili",
    "Πέτρος Σαμαράς",
    "Саша Петровић",
    "Сяргей Снапкоўскі",
    "Վահրամ Չալաբեան",
    "عبدالله رضوان",
    "博仁 林",
    "张诚",
    "浩翔 赵",
    "玉堂白鹤",
    "黃柏諺",
);
?>
