<?php
/*
 * THIS FILE IS AUTOMATICALLY GENERATED BY http://translations.xfce.org
 * DO NOT EDIT IT MANUALLY!
 */

$translators_stamp = "2011-04-24 00:00:08";

$translators = array (
  'Amharic [am]' => array (
    'Tegegne Tefera' => 'tefera'.ATSIGN.'mekuria'.DOTSIGN.'com',
    'Fantaw Tesema' => 'fantaw'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Arabic [ar]' => array (
    'Hasen il Judy' => 'hasan'.DOTSIGN.'aljudy'.ATSIGN.'gmail'.DOTSIGN.'com',
    'كريم أولاد الشلحة' => 'herr'.DOTSIGN.'linux88'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Asturian [ast]' => array (
    'Iñigo Varela' => 'malditoastur'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Belarusian [be]' => array (
    'Andrei Zakharevich' => 'andrej'.ATSIGN.'zahar'.DOTSIGN.'ws',
  ),
  'Bulgarian [bg]' => array (
    'Valentin Tunev' => 'hdbuster'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Hristo Bozhkov' => 'biernywidz'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Bengali [bn]' => array (
    'Jamil Ahmed' => 'itsjamil'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Bengali (India) [bn_IN]' => array (
    'Runa Bhattacharjee' => 'runabh'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sankarshan Mukhopadhyay' => 'sankarshan'.ATSIGN.'randomink'.DOTSIGN.'org',
  ),
  'Catalan (Valencian) [ca]' => array (
    'Carles Muñoz Gorriz' => 'carlesmu'.ATSIGN.'internautas'.DOTSIGN.'org',
    'Harald Servat' => 'redcrash'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Czech [cs]' => array (
    'Michal Várady' => 'miko'.DOTSIGN.'vaji'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Miro Hrončok' => 'miro'.ATSIGN.'hroncok'.DOTSIGN.'cz',
    'David Štancl' => 'dstancl'.ATSIGN.'dstancl'.DOTSIGN.'cz',
    'Jakub Špirk' => 'spirk'.DOTSIGN.'jakub'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Danish [da]' => array (
    'Per Kongstad' => 'p_kongstad'.ATSIGN.'op'.DOTSIGN.'pl',
    'Morten Juhl-Johansen Zölde-Fejér' => 'mjjzf'.ATSIGN.'syntaktisk'.DOTSIGN.'dk',
    'tbesand' => 'thomas'.DOTSIGN.'besand'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'German [de]' => array (
    'Christoph Wickert' => 'christoph'.DOTSIGN.'wickert'.ATSIGN.'googlemail'.DOTSIGN.'com',
    'Mark Trompell' => 'mark'.ATSIGN.'foresightlinux'.DOTSIGN.'org',
    'Matthias Mailänder' => 'matthias'.ATSIGN.'mailaender'.DOTSIGN.'name',
    'Michael Spahn' => 'any0n3'.ATSIGN.'fedoraproject'.DOTSIGN.'org',
    'Christian Weiske' => 'cweiske'.ATSIGN.'cweiske'.DOTSIGN.'de',
    'Johannes Lips' => 'johannes'.DOTSIGN.'lips'.ATSIGN.'googlemail'.DOTSIGN.'com',
    'Hubert Hesse' => 'hub'.ATSIGN.'hubertscorner'.DOTSIGN.'de',
    'Paul Seyfert' => 'pseyfert'.ATSIGN.'mathphys'.DOTSIGN.'fsk'.DOTSIGN.'uni-heidelberg'.DOTSIGN.'de',
    'Knuth Gurkasch' => 'knuth'.ATSIGN.'sinn3r'.DOTSIGN.'org',
    'Fabian Nowak' => 'timystery'.ATSIGN.'arcor'.DOTSIGN.'de',
  ),
  'Greek [el]' => array (
    'Evaggelos Balaskas' => 'ebalaskas'.ATSIGN.'ebalaskas'.DOTSIGN.'gr',
    'Stavros Giannouris' => 'stavrosg'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ioannis Daliakopoulos' => 'yannis'.ATSIGN.'farm'.DOTSIGN.'gr',
    'forfolias' => 'forfolias'.ATSIGN.'gmail'.DOTSIGN.'com',
    'gapan' => 'vlahavas'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Mario Andonoudiou' => 'supermodmusic'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Spiros Georgaras' => 'sng'.ATSIGN.'hellug'.DOTSIGN.'gr',
  ),
  'English (United Kingdom) [en_GB]' => array (
    'Jeff Bailes' => 'thepizzaking'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Spanish (Castilian) [es]' => array (
    'Abel Martín' => 'abel'.DOTSIGN.'martin'.DOTSIGN.'ruiz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Javier Sánchez Reinosa' => 'donoban'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ignacio Velasco' => 'elega'.ATSIGN.'elega'.DOTSIGN.'com'.DOTSIGN.'ar',
    'Gonzalo Lagos' => 'xalo'.DOTSIGN.'em'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Spanish (Argentinian) [es_AR]' => array (
    'Diego Augusto Molina' => 'diegoaugustomolina'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Basque [eu]' => array (
    'Piarres Beobide' => 'pi'.ATSIGN.'beobide'.DOTSIGN.'net',
  ),
  'Persian [fa]' => array (
    'Ehsan Akhlaghi' => 'esnka'.ATSIGN.'yahoo'.DOTSIGN.'com',
  ),
  'Finnish [fi]' => array (
    'Jari Rahkonen' => 'jari'.DOTSIGN.'rahkonen'.ATSIGN.'pp1'.DOTSIGN.'inet'.DOTSIGN.'fi',
  ),
  'French [fr]' => array (
    'Mike Massonnet' => 'mmassonnet'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Steve Dodier' => 'sidnioulz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Durand-Favreau Arnaud' => 'biginoz'.ATSIGN.'free'.DOTSIGN.'fr',
    'magicrhesus' => 'magicrhesus'.ATSIGN.'ouranos'.DOTSIGN.'be',
    'Maximilian Schleiss' => 'maximilian'.ATSIGN.'xfce'.DOTSIGN.'org',
    'marc doutreloux' => 'mdoutreloux'.ATSIGN.'yahoo'.DOTSIGN.'fr',
    'douart patrick' => 'patrick'.DOTSIGN.'2'.ATSIGN.'laposte'.DOTSIGN.'net',
  ),
  'Galician [gl]' => array (
    'Leandro Regueiro' => 'leandro'.DOTSIGN.'regueiro'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Hebrew [he]' => array (
    'Yaron Shahrabani' => 'sh'.DOTSIGN.'yaron'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Hezy Amiel' => 'open'.ATSIGN.'hezyamiel'.DOTSIGN.'com',
  ),
  'Croatian [hr]' => array (
    'Petar Koretić' => 'petar'.DOTSIGN.'koretic'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ivica Kolić' => 'ikoli'.ATSIGN.'yahoo'.DOTSIGN.'com',
  ),
  'Hungarian [hu]' => array (
    'Gabor Kelemen' => 'kelemeng'.ATSIGN.'gnome'.DOTSIGN.'hu',
  ),
  'Armenian [hy]' => array (
    'sssilver' => 'sssilver'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Indonesian [id]' => array (
    'Andhika Padmawan' => 'andhika'.DOTSIGN.'padmawan'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ardjuna' => 'ard_h_r'.ATSIGN.'yahoo'.DOTSIGN.'com',
  ),
  'Icelandic [is]' => array (
    'sveinki' => 'sveinki'.ATSIGN.'nett'.DOTSIGN.'is',
  ),
  'Italian [it]' => array (
    'gianluca foddis' => 'gianluca'.DOTSIGN.'foddis'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Giuseppe D\'Andrea' => 'cryptstudent'.ATSIGN.'yahoo'.DOTSIGN.'com',
    'Leonardo Totaro' => 'elleti'.DOTSIGN.'brainvision'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Cristian Marchi' => 'cri'.DOTSIGN.'penta'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Cristian Cozzolino' => 'cristiancozzolino'.ATSIGN.'libero'.DOTSIGN.'it',
    'maluc' => 'incjsp'.ATSIGN.'yahoo'.DOTSIGN.'it',
    'Riccardo Magini' => 'rcrmgn'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergio Spinatelli' => 'eseasonsapp'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Japanese [ja]' => array (
    'Masato Hashimoto' => 'hashimo'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Nobuhiro Iwamatsu' => 'iwamatsu'.ATSIGN.'nigauri'.DOTSIGN.'org',
  ),
  'Kazakh [kk]' => array (
    'Bauzhan Muftakhidinov' => 'baurthefirst'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Kannada [kn]' => array (
    'shankar' => 'prasad'.DOTSIGN.'mvs'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Vasudev Kamath' => 'kamathvasudev'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Korean [ko]' => array (
    'Boram Kim' => 'boramism'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Lithuanian [lt]' => array (
    'Ričardas Vasiulis' => 'ricardas'.DOTSIGN.'v'.ATSIGN.'inbox'.DOTSIGN.'lt',
  ),
  'Latvian [lv]' => array (
    'Rihards Prieditis' => 'rprieditis'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Norwegian Bokmal [nb]' => array (
    'Terje Uriansrud' => 'terje'.ATSIGN.'uriansrud'.DOTSIGN.'net',
  ),
  'Dutch (Flemish) [nl]' => array (
    'Vincent Tunru' => 'projects'.ATSIGN.'vinnl'.DOTSIGN.'nl',
    'Nick Schermer' => 'nick'.ATSIGN.'xfce'.DOTSIGN.'org',
    'padv' => 'pascal'.DOTSIGN.'devuyst'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Timo Verbeek' => 'timoverbeek10'.ATSIGN.'hotmail'.DOTSIGN.'com',
  ),
  'Norwegian Nynorsk [nn]' => array (
    'Eskild Hustvedt' => 'user'.ATSIGN.'zerodogg'.DOTSIGN.'org',
  ),
  'Panjabi (Punjabi) [pa]' => array (
    'A S Alam' => 'apreet'.DOTSIGN.'alam'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Polish [pl]' => array (
    'Piotr Sokół' => 'psokol'.ATSIGN.'jabster'.DOTSIGN.'pl',
    'Ireneusz Gierlach' => 'irek'.DOTSIGN.'gierlach'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Jeremy Nicolas' => 'jerekpl'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Tomasz Chudyk' => 'chudyk'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Portuguese [pt]' => array (
    'Nuno Miguel' => 'nunis'.ATSIGN.'netcabo'.DOTSIGN.'pt',
    'Bruno Ramos' => 'brunoramos'.DOTSIGN.'lu'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Joel Patrão' => 'joel'.DOTSIGN.'patrao'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergio Marques' => 'smarquespt'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Portuguese (Brazilian) [pt_BR]' => array (
    'Og Maciel' => 'ogmaciel'.ATSIGN.'gnome'.DOTSIGN.'org',
    'Henrique P'.DOTSIGN.' Machado' => 'zehrique'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sérgio Cipolla' => 'secipolla'.ATSIGN.'gmail'.DOTSIGN.'com',
    'tschertel' => 'tschertel'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Vladimir Melo' => 'vladimirmelo'.DOTSIGN.'psi'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Michael Martins' => 'michaelfm21'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Romanian [ro]' => array (
    'Mișu Moldovan' => 'dumol'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Andrei Popescu' => 'andreimpopescu'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergiu Mihai' => 'sergiu'.DOTSIGN.'mihai'.ATSIGN.'devlibre'.DOTSIGN.'net',
  ),
  'Russian [ru]' => array (
    'Dmitrij Smirnov' => 'other'.ATSIGN.'igus'.DOTSIGN.'lv',
    '0leg' => 's'.ATSIGN.'0leg'.DOTSIGN.'me',
    'Alexander Yashkin' => 'alex'.DOTSIGN.'aspirine'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Claque' => 'cpt-alatriste'.ATSIGN.'ya'.DOTSIGN.'ru',
    'Styopa Semenukha' => 'semenukha'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Aleksandr Ponomarenko' => 'davian818'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ivan Nikolaev' => 'voidexp'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Anton Batenev' => 'antonbatenev'.ATSIGN.'yandex'.DOTSIGN.'ru',
    'Evgeniy Kosov' => 'eugene'.ATSIGN.'kosov'.DOTSIGN.'net',
    'Vlad Vasilev' => 'lortwer'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Alexander Matveyev' => 'a'.DOTSIGN.'s'.DOTSIGN.'matveyev'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Denis Koryavov' => 'dkoryavov'.ATSIGN.'yandex'.DOTSIGN.'ru',
    'Andres Kovtunos' => 'kovtunos'.ATSIGN.'yandex'.DOTSIGN.'ru',
    'Dmitriy Kudryashov' => 'overmailed'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Sergey Abramkin' => 'sergey'.ATSIGN.'abramk'.DOTSIGN.'in',
    'ton' => 'tonawuda'.ATSIGN.'inbox'.DOTSIGN.'ru',
    'Victor Homyakov' => 'homyakov'.ATSIGN.'isida'.DOTSIGN.'by',
  ),
  'Sinhala [si]' => array (
    'Danishka Navin' => 'danishka'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Anandawardhana' => 'anandawardhana'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Akila Wajirasena' => 'akila'.DOTSIGN.'wajirasena'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Kalpa Pathum Welivitigoda' => 'callkalpa'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Prabath Galagamage' => 'gprabath'.ATSIGN.'gmail'.DOTSIGN.'com',
    'kasundigital' => 'kasunindika'.ATSIGN.'gmail'.DOTSIGN.'com',
    'kpgtharaka' => 'kpgtharaka'.ATSIGN.'gmail'.DOTSIGN.'com',
    'rashan' => 'rashan'.DOTSIGN.'uoc'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Slovak [sk]' => array (
    'Robert Hartl' => 'hartl'.DOTSIGN.'robert'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Michal Löffler' => 'lofflermichalloffler'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Slovenian [sl]' => array (
    'Alan Pepelko' => 'alan'.DOTSIGN.'pepelko'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Albanian [sq]' => array (
    'Besnik Bleta' => 'besnik'.ATSIGN.'programeshqip'.DOTSIGN.'org',
  ),
  'Serbian [sr]' => array (
    'mpopovic' => 'gpopac'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Nikola Milosavljevic' => 'minikola'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Serbian (Latin) [sr@latin]' => array (
    'Uros Lukic' => 'uroslukic'.ATSIGN.'hotmail'.DOTSIGN.'com',
  ),
  'Swedish [sv]' => array (
    'Daniel Nylander' => 'po'.ATSIGN.'danielnylander'.DOTSIGN.'se',
  ),
  'Tamil [ta]' => array (
    'Mohan R' => 'mohan43u'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Telugu [te]' => array (
    'Praveen Illa' => 'mail2ipn'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Tagalog [tl]' => array (
    'Manuel Oliva' => 'oliva'.DOTSIGN.'manuel'.ATSIGN.'ymail'.DOTSIGN.'com',
  ),
  'Turkish [tr]' => array (
    'Gökmen Görgen' => 'gkmngrgn'.ATSIGN.'gmail'.DOTSIGN.'com',
    'gokmen' => 'gokmen'.ATSIGN.'alageek'.DOTSIGN.'com',
    'Avatar' => 'coskuno_99'.ATSIGN.'yahoo'.DOTSIGN.'com',
    'Ertuğrul HAZAR' => 'ertugrulhazar'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Hafzullah' => 'hafzullah'.DOTSIGN.'is'.ATSIGN.'windowslive'.DOTSIGN.'com',
    'Murat PINAR' => 'wargasm'.ATSIGN.'archlinux'.DOTSIGN.'us',
    'Akın Ömeroğlu' => 'akin'.ATSIGN.'pardus'.DOTSIGN.'org'.DOTSIGN.'tr',
    'alpertekinalp' => 'alper'.DOTSIGN.'tekinalp'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Aydan Taşdemir' => 'aydantasdemir'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ayhan YALÇINSOY' => 'ayhanyalcinsoy'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Erçin EKER' => 'ercineker'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Eren Türkay' => 'erenturkay'.ATSIGN.'xfce'.DOTSIGN.'org',
    'Gökhan Kılınç' => 'kilincgokhan'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ilker DAGLI' => 'ilker'.ATSIGN.'ilkerdagli'.DOTSIGN.'info',
    'kozdincer' => 'kaanozdincer'.ATSIGN.'gmail'.DOTSIGN.'com',
    'marici' => 'cadthecoder'.ATSIGN.'gmail'.DOTSIGN.'com',
    'martinamca' => 'martinamca'.ATSIGN.'gmail'.DOTSIGN.'com',
    'mesutcank' => 'mesutcank'.ATSIGN.'gmail'.DOTSIGN.'com',
    'necdetyucel' => 'necdetyucel'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Osman Karagöz' => 'osmank3'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ozan Türkyılmaz' => 'ozan'.DOTSIGN.'turkyilmaz'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Özgür Kuru' => 'ozgur'.ATSIGN.'ozgurkuru'.DOTSIGN.'net',
    'Samed Beyribey' => 'beyribey'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Senol Korkmaz' => 'mail'.ATSIGN.'senolkorkmaz'.DOTSIGN.'info',
    'Server Acim' => 'serveracim'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Utku Aydın' => 'utkuaydin'.ATSIGN.'archlinux'.DOTSIGN.'org'.DOTSIGN.'tr',
    'vlyalcin' => 'naklovnak'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Uyghur [ug]' => array (
    'Gheyret Kenji' => 'gheyret'.ATSIGN.'yahoo'.DOTSIGN.'com',
    'Abduqadir Abliz' => 'sahran'.ATSIGN.'live'.DOTSIGN.'com',
  ),
  'Ukrainian [uk]' => array (
    'Dmitry Nikitin' => 'luckas_fb'.ATSIGN.'mail'.DOTSIGN.'ru',
    'Yarema aka Knedlyk' => 'yupadmin'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Maxim Dziumanenko' => 'dziumanenko'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Andriy Matkovsky' => 'sidius'.DOTSIGN.'ua'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Urdu [ur]' => array (
    'Irfan Ashraf' => 'visualrange'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Vietnamese [vi]' => array (
    'Vinh Nguyen' => 'kureikain'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Chinese (China) [zh_CN]' => array (
    'Qianqian Fang' => 'fangqq'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ganghua Leng' => 'hiweed'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Hunt Xu' => 'mhuntxu'.ATSIGN.'gmail'.DOTSIGN.'com',
    'Ivy Lee' => 'ivyleexyg'.ATSIGN.'gmail'.DOTSIGN.'com',
    '微 尘' => 'yjwork'.DOTSIGN.'xfce'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
  'Chinese (Taiwan) [zh_TW]' => array (
    'Cheng-Chia Tseng' => 'pswo10680'.ATSIGN.'gmail'.DOTSIGN.'com',
  ),
);
?>
