Bernhard Walle (bernhard.walle at gmx.de)<br>
Biju Chacko (botsie at myrealbox.com)<br>
Craig Betts (craig.betts at dfrc.nasa.gov)<br>
Ejvend Nielsen (prophet at sphere-x.net)<br>
Erik Touve (etouve at earthlink.net)<br>
Jens Guballa (j.guballa at t-online.de)<br>
Jens Luedicke (jens at irs-net.com)<br>
Joakim Andreasson (joakim.andreasson at gmx.net)<br>
Joe Klemmer (klemmerj at webtrek.com)<br>
Karsten Luetkewitz (phrep at plskthx.org)<br>
Martin Loschwitz (madkiss at debian.org)<br>
Michael Mosier (michael at spyonit.com)<br>
Mickaël Graf (korbinus at xfce.org)<br>
Thomas Leonard (tal00r at ecs.soton.ac.uk)<br>
Tobias Henle (tobias at page23.de)<br>
Xavier Maillard (zedek at gnu-rox.org)<br>
