<li>gtk-xfce-engine-2</li>
<li>installit</li>
<li>libexo</li>
<li>libxfce4mcs</li>
<li>libxfce4util</li>
<li>libxfcegui4</li>
<li>mousepad</li>
<li>pyxfce</li>
<li>terminal</li>
<li>thunar</li>
<li>xarchiver</li>
<li>xfburn</li>
<li>xfc</li>
<li>xfcalendar</li>
<li>xfce-installers<li>
<li>xfce-mcs-manager</li>
<li>xfce-mcs-plugins</li>
<li>xfce-utils</li>
<li>xfce4-appfinder</li>
<li>xfce4-dev-tools</li>
<li>xfce4-icon-theme</li>
<li>xfce4-mailwatch-plugin</li>
<li>xfce4-mixer</li>
<li>xfce4-panel</li>
<li>xfce4-session</li>
<li>xfce4-terminal</li>
<li>xfce4-toys</li>
<li>xfce4-trigger-launcher</li>
<li>xfdesktop</li>
<li>xffm</li>
<li>xfmedia</li>
<li>xfprint</li>
<li>xfwm4</li>
<li>xfwm4-themes</li>
