<html><head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>
  The Xfce 4 Desktop Environment
</title><link rel="stylesheet" href="../xfce.css" type="text/css"><meta name="generator" content="DocBook XSL Stylesheets V1.66.1"><link rel="start" href="xfce4-user-guide.html" title="
  The Xfce 4 Desktop Environment
"><link rel="next" href="xfce4-intro.html" title="Introduction"></head><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">
  The Xfce 4 Desktop Environment
</th></tr><tr><td width="20%" align="left"> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="xfce4-intro.html">Next</a></td></tr></table><hr></div><div class="article" lang="en"><div class="titlepage"><div><div><h1 class="title"><a name="xfce4-user-guide"></a>
  The Xfce 4 Desktop Environment
</h1></div><div><h3 class="subtitle"><i>
  <img src="images/link_xfce.jpg">
  <span class="emphasis"><em>... and mice fly ...</em></span>
</i></h3></div><div><div class="authorgroup"><div class="author"><h3 class="author"><span class="firstname">Jasper</span> <span class="surname">Huijsmans</span></h3><div class="affiliation"><div class="address"><p><tt class="email">&lt;<a href="mailto:jasper@xfce.org">jasper@xfce.org</a>&gt;</tt></p></div></div></div><div class="author"><h3 class="author"><span class="firstname">Benedikt</span> <span class="surname">Meurer</span></h3><div class="affiliation"><div class="address"><p><tt class="email">&lt;<a href="mailto:benny@xfce.org">benny@xfce.org</a>&gt;</tt></p></div></div></div></div></div><div><p class="copyright">Copyright © 2004 Jasper Huijsmans</p></div></div><hr></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="sect1"><a href="xfce4-user-guide.html#preface">Preface</a></span></dt><dt><span class="sect1"><a href="xfce4-intro.html">Introduction</a></span></dt><dd><dl><dt><span class="sect2"><a href="xfce4-intro.html#xfce4-resources">Resources</a></span></dt></dl></dd><dt><span class="sect1"><a href="xfce4-use.html">Using Xfce4</a></span></dt><dd><dl><dt><span class="sect2"><a href="xfce4-use.html#xfce4-getting-started">Getting started</a></span></dt><dt><span class="sect2"><a href="xfce4-use.html#id2533342">The Default Desktop</a></span></dt><dt><span class="sect2"><a href="xfce4-use.html#id2533998">Common Tasks</a></span></dt><dt><span class="sect2"><a href="xfce4-use.html#id2534182">Further reading</a></span></dt></dl></dd><dt><span class="sect1"><a href="xfce4-components.html">Components of Xfce 4</a></span></dt><dt><span class="sect1"><a href="xfce4-install.html">Installing Xfce4</a></span></dt><dd><dl><dt><span class="sect2"><a href="xfce4-install.html#id2534533">Binary packages</a></span></dt><dt><span class="sect2"><a href="xfce4-install.html#id2534968">Graphical installers</a></span></dt><dt><span class="sect2"><a href="xfce4-install.html#id2534990">Building from source</a></span></dt><dt><span class="sect2"><a href="xfce4-install.html#id2535072">Using CVS</a></span></dt><dt><span class="sect2"><a href="xfce4-install.html#id2596877">Additional software</a></span></dt></dl></dd><dt><span class="sect1"><a href="xfce4-copyright.html">Copyright and Licences</a></span></dt><dt><span class="sect1"><a href="BSD.html">BSD License</a></span></dt><dt><span class="sect1"><a href="GPL.html">GNU General Public License</a></span></dt><dt><span class="sect1"><a href="LGPL.html">GNU Library General Public License</a></span></dt></dl></div><div class="sect1" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both"><a name="preface"></a>Preface</h2></div></div></div><p>
    This document gives an overview of the Xfce 4 Desktop Environment and
    explains how to perform several common tasks. It is meant to be a starting
    point for anyone who wants to use Xfce 4 and it includes pointers
    to other sources of information.
  </p><p>
    The latest version of this document can always be found at 
<a href="http://www.loculus.nl/xfce/documentation/" target="_top">this location</a>.
  </p></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="xfce4-intro.html">Next</a></td></tr><tr><td width="40%" align="left" valign="top"> </td><td width="20%" align="center"> </td><td width="40%" align="right" valign="top"> Introduction</td></tr></table></div></body></html>
